### ISSUE TITLE
No RSS/Atom feed found for blog

### ISSUE THREAD

**Issue by brantonb** [GregDomzalski/GregDomzalski.github.io#3]
I'm trying to build up my RSS reader with interesting content. I tried finding a feed for your blog, but was unable to. My reader couldn't discover one from the headers, either. I haven't used Hugo before, but it looks like it should be pretty straightforward:

https://gohugo.io/templates/rss/

Looks like it was attempted via the [enableRSS = true](https://github.com/GregDomzalski/GregDomzalski.github.io/blob/0e48598d32bf50437602c2c213e0a888f05bb0a6/hugo.toml#L15) line in `hugo.toml`, but I wasn't able to find any feeds.

And here are some header tags that help feed readers auto-discover the feed(s).

```html
<head>
    <link rel="alternate" type="application/rss+xml" title="Awesome Sauce Blog - RSS feed" href="/rss.xml">
    <link rel="alternate" type="application/atom+xml" title="Awesome Sauce Blog - Atom feed" href="/atom.xml">
    <link rel="alternate" type="application/json" title="Awesome Sauce Blog - JSON feed" href="/feed.json">
</head>
```

If this gets added, I'd definitely subscribe.

**Comment by GregDomzalski** [comment]
Thanks! Yeah. Blog has been a slow roll out in my free time. I do hope to start posting more - as well as adding more features. Exposure was definitely my goal with finally revamping my personal domain. I was shocked to see anyone notice so soon :smile: 

I'll take a look sometime this week. With most of the holidays behind me, I should have _some_ free time to start building out more features.

**Comment by GregDomzalski** [comment]
Looks like the blog post feed is here: https://gregdom.com/posts/index.xml

I'll add the header links and shut off the default feeds for things that don't need it.

**Comment by GregDomzalski** [comment]
OK - added the header links in 70479fdae

Should hopefully be more discoverable now. :smile: 

I'll try and only write interesting posts. If there are other blogs you'd like to share - lemme know! I'm always on the hunt for good ones too. Especially if they're from former colleagues :grin:

**Comment by brantonb** [comment]
Subscribed!! Thanks so much.
